mod sale;
mod transactions;
mod items;
mod categories;
mod reports;
mod kitchen;
mod login;
mod admin;
mod setup;
pub mod keyboard;

pub use sale::SalePage;
pub use transactions::TransactionsPage;
pub use items::ItemsPage;
pub use categories::CategoriesPage;
pub use reports::ReportsPage;
pub use kitchen::KitchenPage;
pub use login::LoginPage;
pub use admin::AdminPage;
pub use setup::SetupPage;
